"""Shared config + data-loading utilities for the roughness-scaling analysis.

The simulation (slopeDistFast) writes, per recorded step, the height profile as a
comma-separated list of local slopes m_i = h_{i+1} - h_i.  The interface width is
W(t) = std of the reconstructed height profile (additive constant irrelevant).

All data now lives under this folder's outputs/slopeDist (generated by run_sweep.py).
"""
import glob
import os
import re
import numpy as np

ROUGH = os.path.dirname(os.path.abspath(__file__))  # this folder (rename-proof)
DATA = f"{ROUGH}/outputs/slopeDist"
PLOTS = f"{ROUGH}/plots"

# ---------------------------------------------------------------------------
# Sweep definition (single source of truth for generation AND analysis).
# steps sized so the largest L saturates; H bounds the pile (v ~ 1 - 5.24/N);
# gw = growth-fit window for beta; Ls = system sizes run for that N.
# ---------------------------------------------------------------------------
FSWEEP = {
    6:  dict(steps=20000,  H=4736,   gw=(5, 80),    Ls=[16, 32, 64, 128, 256]),
    7:  dict(steps=24000,  H=8400,   gw=(6, 110),   Ls=[16, 32, 64, 128, 256]),
    8:  dict(steps=34000,  H=14400,  gw=(8, 160),   Ls=[16, 32, 64, 128, 256]),
    9:  dict(steps=45000,  H=21760,  gw=(9, 220),   Ls=[16, 32, 64, 128]),
    10: dict(steps=60000,  H=32000,  gw=(10, 300),  Ls=[16, 32, 64, 128]),
    12: dict(steps=90000,  H=55296,  gw=(12, 450),  Ls=[16, 32, 64, 128]),
    15: dict(steps=140000, H=97792,  gw=(15, 700),  Ls=[16, 32, 64, 128]),
    20: dict(steps=200000, H=157184, gw=(20, 1200), Ls=[16, 32, 64, 128]),
}
# extra large-N at L=64 only, to extend the slope-PDF / growth-exponent family
LEXTRA = {
    30: dict(steps=16000, H=16000),
    40: dict(steps=16000, H=16640),
}
NSIMS = 48
FIXED_L = 64  # column used for the slope-PDF and growth-exponent families

_INT = re.compile(r"-?\d+")


def steps_of(N):
    return FSWEEP[N]["steps"] if N in FSWEEP else LEXTRA[N]["steps"]


def pattern(L, N):
    """Glob for all sims of a given (L, N)."""
    return f"{DATA}/L_{L}_N_{N}_steps_{steps_of(N)}_sim_*.tsv"


def parse_slopes(field):
    return np.array(_INT.findall(field), dtype=float)


def roughness_series(path):
    """Return (steps, W(t)) for one simulation file."""
    t, W = [], []
    with open(path) as fh:
        next(fh)
        for line in fh:
            p = line.split("\t")
            if len(p) < 3 or not p[2].strip():
                continue
            s = parse_slopes(p[2].strip())
            h = np.concatenate(([0.0], np.cumsum(s[:-1])))
            t.append(float(p[0]))
            W.append(np.std(h))
    return np.array(t), np.array(W)


def stack(L, N):
    """Stack W(t) over all sims for (L, N). Returns (t, W[sim, t]) or (None, None)."""
    files = sorted(glob.glob(pattern(L, N)))
    if not files:
        return None, None
    ref, rows = None, []
    for f in files:
        t, w = roughness_series(f)
        if ref is None:
            ref = t
        rows.append(w[:min(len(ref), len(w))])
    n = min(len(r) for r in rows)
    return ref[:n], np.array([r[:n] for r in rows])


def mean_W(L, N):
    t, W = stack(L, N)
    return (t, W.mean(0)) if t is not None else (None, None)


def all_N_at_fixed_L():
    """N values that have L=FIXED_L data, sorted (for slope-PDF / beta_eff)."""
    return sorted(list(FSWEEP) + list(LEXTRA))
